### ISSUE TITLE
Ability to restrict the partials available to a specific collection.

### ISSUE THREAD

**Issue by Zoramite** [grow/grow-ext-editor#1]
Currently all partials are available to be added to any content. One improvement would be to allow for only filtered set of partials to be available based on the collection configuration.

For example:

```
fields:
- type: text
  key: $title
  label: Title

partials:
  filters:
  # Don't allow editing any partials that start with `hero`.
  - type: blacklist
    values:
    - hero*
  # Only allow editing specific partials.
  - type: whitelist
    values:
    - tout
    - gallery
```
