### ISSUE TITLE
Failed validation should prevent saves

### ISSUE THREAD

**Issue by uxder** [grow/grow-ext-editor#122]
We discussed this but I wanted to add it here so we can track it.

```
  - type: list
    key: cards
    label: 3up Cards
    preview_field: title
    validation:
    - type: length
      max:
        value: 3
        message: Cannot have more than 3.
  ```

The above currently shows a validation error but still does not prevent you from saving a 4th item.  Hitting "Add" will add a new item.

![screenshot 2020-12-16 at 6 15 19](https://user-images.githubusercontent.com/7152/102273724-21ba3e80-3f66-11eb-92fd-9eb75bbe72bd.jpg)

Can we:
- remove the button validation fails
- prevent saving when validation fails
