### ISSUE TITLE
Empty type: document throws a JS error

### ISSUE THREAD

**Issue by uxder** [grow/grow-ext-editor#68]
Saving with an empty "document" type after it is defined throws a JS error.

I have the following schema:

```
cta:
....
- type: document
  key: internal_doc
  label: Internal Link
- type: text
  key: url
  label: External URL
```

1) Save something in the document field.
![screenshot 2020-05-21 at 9 38 31](https://user-images.githubusercontent.com/7152/82511116-66ecce00-9b47-11ea-96a0-c381db4b2a18.jpg)

2) Now go back and fully delete it and then try saving.
![screenshot 2020-05-21 at 9 42 17](https://user-images.githubusercontent.com/7152/82511114-62281a00-9b47-11ea-88d3-f750e30b6b2f.jpg)

3) You'll notice it throws an error.

![screenshot 2020-05-21 at 9 41 41](https://user-images.githubusercontent.com/7152/82511091-52103a80-9b47-11ea-864c-f326a1b3bca7.jpg)
