### ISSUE TITLE
Adding a list length limit

### ISSUE THREAD

**Issue by uxder** [grow/grow-ext-editor#70]
Minor feature request but pretty low priority.

It's common to have a list of content in cases of things like, touts, carousels, tabs etc.  Some layouts such as a 3up touts module may not expect more than 3 items in the list.  It would be nice to be able to define a list length limit preventing editors from adding more than that number.

Might be like `max`?
```
  - type: list
    label: 3up Cards
    max: 3
    fields:
     ...
```

**Comment by Zoramite** [comment]
Thanks, I think I will end up doing this with the validation we have planned... something like this:

```yaml
- type: list
  label: Cards
  validation:
    max: 3
    min: 1
  fields: ...
```
