### ISSUE TITLE
When using markdown field in a list only the first list item gets the markdown changes.

### ISSUE THREAD

**Issue by Zoramite** [grow/grow-ext-editor#75]
For some reason when using the markdown field in a list the markdown is only showing the first item in the list.

Example config:

```
- key: sections
  type: list
  label: FAQs
  fields:
  - key: title.text@
    type: text
    label: Question
  - key: body.text@
    type: markdown
    label: Answer
```
