### ISSUE TITLE
[object Object] sometimes visible with !g.string

### ISSUE THREAD

**Issue by jeremydw** [grow/grow-ext-editor#77]
We should never have any instance of `[object Object]` appearing in the editor UI – even if the type doesn't match the value, it shouldn't serialize to `[object Object]`

![image](https://user-images.githubusercontent.com/646525/83802545-d098cc00-a65f-11ea-919e-d021d62cd559.png)

In the page YAML:

```
$title@: !g.string homepage.page_title.string
description@: !g.string homepage.page_description.string
```

In the `_editor.yaml`:

```
fields:
- type: text
  key: $title@
  label: Page title
- type: textarea
  key: description@
  label: Meta description
```
